-- Oracle DDL for JobRunr Control parameter sets table
-- Create this table manually before using external parameter storage
-- This script is idempotent and can be run multiple times safely

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists
    FROM user_tables
    WHERE table_name = 'JOBRUNR_CONTROL_PARAMETER_SETS';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE "JOBRUNR_CONTROL_PARAMETER_SETS" (
                "ID" VARCHAR2(36) PRIMARY KEY NOT NULL,
                "JOB_TYPE" VARCHAR2(500) NOT NULL,
                "PARAMETERS_JSON" CLOB NOT NULL,
                "CREATED_AT" TIMESTAMP NOT NULL,
                "UPDATED_AT" TIMESTAMP NOT NULL,
                "VERSION" NUMBER(19)
            )
        ';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_param_set_job_type ON "JOBRUNR_CONTROL_PARAMETER_SETS"("JOB_TYPE")';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_param_set_created ON "JOBRUNR_CONTROL_PARAMETER_SETS"("CREATED_AT")';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_param_set_updated ON "JOBRUNR_CONTROL_PARAMETER_SETS"("UPDATED_AT")';
        EXECUTE IMMEDIATE 'COMMENT ON TABLE "JOBRUNR_CONTROL_PARAMETER_SETS" IS ''Stores job parameter sets for JobRunr Control external parameter storage''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN "JOBRUNR_CONTROL_PARAMETER_SETS"."ID" IS ''Unique identifier (UUID)''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN "JOBRUNR_CONTROL_PARAMETER_SETS"."JOB_TYPE" IS ''Fully qualified job class name''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN "JOBRUNR_CONTROL_PARAMETER_SETS"."PARAMETERS_JSON" IS ''Job parameters stored as JSON''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN "JOBRUNR_CONTROL_PARAMETER_SETS"."CREATED_AT" IS ''Timestamp when the parameter set was created''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN "JOBRUNR_CONTROL_PARAMETER_SETS"."UPDATED_AT" IS ''Timestamp when the parameter set was last updated''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN "JOBRUNR_CONTROL_PARAMETER_SETS"."VERSION" IS ''Optimistic locking version''';
        DBMS_OUTPUT.PUT_LINE('Table "JOBRUNR_CONTROL_PARAMETER_SETS" created successfully.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Table "JOBRUNR_CONTROL_PARAMETER_SETS" already exists, skipping.');
    END IF;

    SELECT COUNT(*) INTO table_exists
    FROM user_tables
    WHERE table_name = 'JOBRUNR_CONTROL_BATCH_RECAP';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE "JOBRUNR_CONTROL_BATCH_RECAP" (
                "BATCH_JOB_ID" VARCHAR2(36) NOT NULL,
                "CHILD_JOB_ID" VARCHAR2(36) NOT NULL,
                "COUNTER_NAME" VARCHAR2(255) NOT NULL,
                "COUNTER_VALUE" NUMBER(19) DEFAULT 0 NOT NULL,
                CONSTRAINT pk_jobrunr_control_batch_recap PRIMARY KEY ("BATCH_JOB_ID", "CHILD_JOB_ID", "COUNTER_NAME")
            )
        ';
        EXECUTE IMMEDIATE 'COMMENT ON TABLE "JOBRUNR_CONTROL_BATCH_RECAP" IS ''Recap counters per child job in a batch''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN "JOBRUNR_CONTROL_BATCH_RECAP"."BATCH_JOB_ID" IS ''Batch job identifier (UUID)''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN "JOBRUNR_CONTROL_BATCH_RECAP"."CHILD_JOB_ID" IS ''Child job identifier (UUID)''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN "JOBRUNR_CONTROL_BATCH_RECAP"."COUNTER_NAME" IS ''Recap counter name''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN "JOBRUNR_CONTROL_BATCH_RECAP"."COUNTER_VALUE" IS ''Counter value for one child job''';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_batch_recap_agg ON "JOBRUNR_CONTROL_BATCH_RECAP"("BATCH_JOB_ID", "COUNTER_NAME", "COUNTER_VALUE")';
        DBMS_OUTPUT.PUT_LINE('Table "JOBRUNR_CONTROL_BATCH_RECAP" created successfully.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Table "JOBRUNR_CONTROL_BATCH_RECAP" already exists, skipping.');
    END IF;

    SELECT COUNT(*) INTO table_exists
    FROM user_tables
    WHERE table_name = 'JOBRUNR_CONTROL_BATCH_MESSAGES';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE "JOBRUNR_CONTROL_BATCH_MESSAGES" (
                "ID" NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                "BATCH_JOB_ID" VARCHAR2(36) NOT NULL,
                "CREATED_AT" TIMESTAMP NOT NULL,
                "LEVEL" VARCHAR2(20) NOT NULL,
                "MESSAGE" CLOB,
                "STACK_TRACE" CLOB
            )
        ';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_batch_msg_created ON "JOBRUNR_CONTROL_BATCH_MESSAGES"("BATCH_JOB_ID", "CREATED_AT")';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_batch_msg_filter ON "JOBRUNR_CONTROL_BATCH_MESSAGES"("BATCH_JOB_ID", "LEVEL", "CREATED_AT")';
        EXECUTE IMMEDIATE 'COMMENT ON TABLE "JOBRUNR_CONTROL_BATCH_MESSAGES" IS ''Batch job log and exception messages''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN "JOBRUNR_CONTROL_BATCH_MESSAGES"."BATCH_JOB_ID" IS ''Batch job identifier (UUID)''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN "JOBRUNR_CONTROL_BATCH_MESSAGES"."CREATED_AT" IS ''Timestamp when the message was created''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN "JOBRUNR_CONTROL_BATCH_MESSAGES"."LEVEL" IS ''Message level (INFO, WARNING, ERROR, EXCEPTION)''';
        DBMS_OUTPUT.PUT_LINE('Table "JOBRUNR_CONTROL_BATCH_MESSAGES" created successfully.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Table "JOBRUNR_CONTROL_BATCH_MESSAGES" already exists, skipping.');
    END IF;
END;
/
EXIT;
