-- Oracle DDL for JobRunr Control parameter sets table
-- Create this table manually before using external parameter storage
-- This script is idempotent and can be run multiple times safely

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists
    FROM user_tables
    WHERE table_name = 'JOBRUNR_CONTROL_PARAMETER_SETS';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE jobrunr_control_parameter_sets (
                id VARCHAR2(36) PRIMARY KEY NOT NULL,
                job_type VARCHAR2(500) NOT NULL,
                parameters_json CLOB NOT NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL,
                version NUMBER(19)
            )
        ';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_param_set_job_type ON jobrunr_control_parameter_sets(job_type)';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_param_set_created ON jobrunr_control_parameter_sets(created_at)';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_param_set_updated ON jobrunr_control_parameter_sets(updated_at)';
        EXECUTE IMMEDIATE 'COMMENT ON TABLE jobrunr_control_parameter_sets IS ''Stores job parameter sets for JobRunr Control external parameter storage''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN jobrunr_control_parameter_sets.id IS ''Unique identifier (UUID)''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN jobrunr_control_parameter_sets.job_type IS ''Fully qualified job class name''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN jobrunr_control_parameter_sets.parameters_json IS ''Job parameters stored as JSON''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN jobrunr_control_parameter_sets.created_at IS ''Timestamp when the parameter set was created''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN jobrunr_control_parameter_sets.updated_at IS ''Timestamp when the parameter set was last updated''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN jobrunr_control_parameter_sets.version IS ''Optimistic locking version''';
        DBMS_OUTPUT.PUT_LINE('Table jobrunr_control_parameter_sets created successfully.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Table jobrunr_control_parameter_sets already exists, skipping.');
    END IF;

    SELECT COUNT(*) INTO table_exists
    FROM user_tables
    WHERE table_name = 'JOBRUNR_CONTROL_BATCH_RECAP';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE jobrunr_control_batch_recap (
                batch_job_id VARCHAR2(36) NOT NULL,
                child_job_id VARCHAR2(36) NOT NULL,
                counter_name VARCHAR2(255) NOT NULL,
                counter_value NUMBER(19) DEFAULT 0 NOT NULL,
                CONSTRAINT pk_jobrunr_control_batch_recap PRIMARY KEY (batch_job_id, child_job_id, counter_name)
            )
        ';
        EXECUTE IMMEDIATE 'COMMENT ON TABLE jobrunr_control_batch_recap IS ''Recap counters per child job in a batch''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN jobrunr_control_batch_recap.batch_job_id IS ''Batch job identifier (UUID)''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN jobrunr_control_batch_recap.child_job_id IS ''Child job identifier (UUID)''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN jobrunr_control_batch_recap.counter_name IS ''Recap counter name''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN jobrunr_control_batch_recap.counter_value IS ''Counter value for one child job''';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_batch_recap_agg ON jobrunr_control_batch_recap(batch_job_id, counter_name, counter_value)';
        DBMS_OUTPUT.PUT_LINE('Table jobrunr_control_batch_recap created successfully.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Table jobrunr_control_batch_recap already exists, skipping.');
    END IF;

    SELECT COUNT(*) INTO table_exists
    FROM user_tables
    WHERE table_name = 'JOBRUNR_CONTROL_BATCH_MESSAGES';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE jobrunr_control_batch_messages (
                id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                batch_job_id VARCHAR2(36) NOT NULL,
                created_at TIMESTAMP NOT NULL,
                level VARCHAR2(20) NOT NULL,
                message CLOB,
                stack_trace CLOB
            )
        ';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_batch_msg_created ON jobrunr_control_batch_messages(batch_job_id, created_at)';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_batch_msg_filter ON jobrunr_control_batch_messages(batch_job_id, level, created_at)';
        EXECUTE IMMEDIATE 'COMMENT ON TABLE jobrunr_control_batch_messages IS ''Batch job log and exception messages''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN jobrunr_control_batch_messages.batch_job_id IS ''Batch job identifier (UUID)''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN jobrunr_control_batch_messages.created_at IS ''Timestamp when the message was created''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN jobrunr_control_batch_messages.level IS ''Message level (INFO, WARNING, ERROR, EXCEPTION)''';
        DBMS_OUTPUT.PUT_LINE('Table jobrunr_control_batch_messages created successfully.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Table jobrunr_control_batch_messages already exists, skipping.');
    END IF;
END;
/
EXIT;
