-- PostgreSQL DDL for JobRunr Control parameter sets table
-- Create this table manually before using external parameter storage

CREATE TABLE IF NOT EXISTS jobrunr_control_parameter_sets (
    id VARCHAR(36) PRIMARY KEY NOT NULL,
    job_type VARCHAR(500) NOT NULL,
    parameters_json JSONB NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT
);

CREATE INDEX IF NOT EXISTS idx_param_set_job_type ON jobrunr_control_parameter_sets(job_type);
CREATE INDEX IF NOT EXISTS idx_param_set_created ON jobrunr_control_parameter_sets(created_at);
CREATE INDEX IF NOT EXISTS idx_param_set_updated ON jobrunr_control_parameter_sets(updated_at);

COMMENT ON TABLE jobrunr_control_parameter_sets IS 'Stores job parameter sets for JobRunr Control external parameter storage';
COMMENT ON COLUMN jobrunr_control_parameter_sets.id IS 'Unique identifier (UUID)';
COMMENT ON COLUMN jobrunr_control_parameter_sets.job_type IS 'Fully qualified job class name';
COMMENT ON COLUMN jobrunr_control_parameter_sets.parameters_json IS 'Job parameters stored as JSON';
COMMENT ON COLUMN jobrunr_control_parameter_sets.created_at IS 'Timestamp when the parameter set was created';
COMMENT ON COLUMN jobrunr_control_parameter_sets.updated_at IS 'Timestamp when the parameter set was last updated';
COMMENT ON COLUMN jobrunr_control_parameter_sets.version IS 'Optimistic locking version';

CREATE TABLE IF NOT EXISTS jobrunr_control_batch_recap (
    batch_job_id VARCHAR(36) NOT NULL,
    child_job_id VARCHAR(36) NOT NULL,
    counter_name VARCHAR(255) NOT NULL,
    counter_value BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (batch_job_id, child_job_id, counter_name)
);
CREATE INDEX IF NOT EXISTS idx_batch_recap_agg ON jobrunr_control_batch_recap(batch_job_id, counter_name, counter_value);

CREATE TABLE IF NOT EXISTS jobrunr_control_batch_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_job_id VARCHAR(36) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    level VARCHAR(20) NOT NULL,
    message TEXT,
    stack_trace TEXT
);

CREATE INDEX IF NOT EXISTS idx_batch_msg_created ON jobrunr_control_batch_messages(batch_job_id, created_at);
CREATE INDEX IF NOT EXISTS idx_batch_msg_filter ON jobrunr_control_batch_messages(batch_job_id, level, created_at);

COMMENT ON TABLE jobrunr_control_batch_recap IS 'Recap counters per child job in a batch';
COMMENT ON COLUMN jobrunr_control_batch_recap.batch_job_id IS 'Batch job identifier (UUID)';
COMMENT ON COLUMN jobrunr_control_batch_recap.child_job_id IS 'Child job identifier (UUID)';
COMMENT ON COLUMN jobrunr_control_batch_recap.counter_name IS 'Recap counter name';
COMMENT ON COLUMN jobrunr_control_batch_recap.counter_value IS 'Counter value for one child job';

COMMENT ON TABLE jobrunr_control_batch_messages IS 'Batch job log and exception messages';
COMMENT ON COLUMN jobrunr_control_batch_messages.batch_job_id IS 'Batch job identifier (UUID)';
COMMENT ON COLUMN jobrunr_control_batch_messages.created_at IS 'Timestamp when the message was created';
COMMENT ON COLUMN jobrunr_control_batch_messages.level IS 'Message level (INFO, WARNING, ERROR, EXCEPTION)';
