-- H2 DDL for JobRunr Control parameter sets table
-- Create this table manually before using external parameter storage

CREATE TABLE IF NOT EXISTS jobrunr_control_parameter_sets (
    id VARCHAR(36) PRIMARY KEY NOT NULL,
    job_type VARCHAR(500) NOT NULL,
    parameters_json JSON NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT
);

CREATE INDEX IF NOT EXISTS idx_param_set_job_type ON jobrunr_control_parameter_sets(job_type);
CREATE INDEX IF NOT EXISTS idx_param_set_created ON jobrunr_control_parameter_sets(created_at);
CREATE INDEX IF NOT EXISTS idx_param_set_updated ON jobrunr_control_parameter_sets(updated_at);

CREATE TABLE IF NOT EXISTS jobrunr_control_batch_recap (
    batch_job_id VARCHAR(36) NOT NULL,
    child_job_id VARCHAR(36) NOT NULL,
    counter_name VARCHAR(255) NOT NULL,
    counter_value BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (batch_job_id, child_job_id, counter_name)
);
CREATE INDEX IF NOT EXISTS idx_batch_recap_agg ON jobrunr_control_batch_recap(batch_job_id, counter_name);

CREATE TABLE IF NOT EXISTS jobrunr_control_batch_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_job_id VARCHAR(36) NOT NULL,
    child_job_id VARCHAR(36),
    created_at TIMESTAMP NOT NULL,
    level VARCHAR(20) NOT NULL,
    message CLOB,
    stack_trace CLOB
);

CREATE INDEX IF NOT EXISTS idx_batch_msg_created ON jobrunr_control_batch_messages(batch_job_id, created_at);
CREATE INDEX IF NOT EXISTS idx_batch_msg_filter ON jobrunr_control_batch_messages(batch_job_id, level, created_at);
